name: "Helm on EKS (with eksctl)"
description: "Authenticates on EKS clusters using eksctl and executes Helm commands. Can also be used with kubectl commands."
branding:
  icon: 'anchor'
  color: 'blue'
inputs:
  command:
    description: "Your command (kubectl or helm)"
    required: true
  plugins:
    description: "Comma-separated URLs for the Helm Plugins you need installed"
    required: false
  eks_cluster:
    description: "Name of your EKS cluster (i.e., from `eksctl get cluster`)"
    required: true
  image:
    description: "Optionally use a pre-built image to save build time"
    required: false
    default: "Dockerfile"
  verbose:
    description: "Enables shell command tracing. Takes string input 'true' or 'false'. Defaults to false."
    required: false
    default: "false"
outputs:
  result:
    description: "Output returned by your Helm or kubectl command"
runs:
  using: "docker"
  image: ${{ input.image }}
  args:
    - ${{ inputs.command }}
